apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: ananke
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.4.0
    helm:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: authorizationpolicies.policy.linkerd.io
      jsonPointers:
        - /spec/names/shortNames
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: meshtlsauthentications.policy.linkerd.io
      jsonPointers:
        - /spec/names/shortNames
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: networkauthentications.policy.linkerd.io
      jsonPointers:
        - /spec/names/shortNames
