apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: ananke
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.4.0
    helm:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
